//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingManagement.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parking_Space
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parking_Space()
        {
            this.Vehicle_Parking = new HashSet<Vehicle_Parking>();
        }
    
        public int Parking_Space_Id { get; set; }
        public string Parking_Space_Title { get; set; }
        public int Parking_Zone_Id { get; set; }
    
        public virtual Parking_Zone Parking_Zone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle_Parking> Vehicle_Parking { get; set; }
    }
}
