//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingManagement.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_Parking
    {
        public int Vehicle_Parking_Id { get; set; }
        public int Parking_Zone_Id { get; set; }
        public int Parking_Space_Id { get; set; }
        public string Booking_Date_Time { get; set; }
        public string Release_Date_Time { get; set; }
        public string Registration_No { get; set; }
        public string Actual_Release_Time { get; set; }
    
        public virtual Parking_Space Parking_Space { get; set; }
        public virtual Parking_Zone Parking_Zone { get; set; }
    }
}
